### 获取验证码
GET http://127.0.0.1:10088/api/v1/pub/login/captchaid
Content-Type: application/json

### 获取图形验证码
GET http://127.0.0.1:10088/api/v1/pub/login/captcha?id=kGAJv0yqAJAJyabcgHvi
Content-Type: application/json

### 用户登录
POST http://127.0.0.1:10088/api/v1/pub/login/
Content-Type: application/json

{
  "captcha_code": "6566",
  "captcha_id": "oYUDUVNlzoH8rkYNL21C",
  "password": "root",
  "user_name": "root"
}

### 测试接口
# curl -X GET "http://127.0.0.1:10088/api/v1/menus?current=1&pageSize=10" -H "accept: application/json" -H "Authorization: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NDE3OTY1NjEsImlhdCI6MTY0MTc4OTM2MSwibmJmIjoxNjQxNzg5MzYxLCJzdWIiOiIxLXJvb3QifQ.iADOw32sNoMOLlHJV-uxm_QiEIPpd6dpDNVeuupYLfTTkwDi9Edv58KuG5Lmszv2fkXkA457dB9FAZsmML-1IQ"
GET http://127.0.0.1:10088/api/v1/menus?current=1&pageSize=10
accept: application/json

###



